export const STORY_ARCHITECTURE_VERSION = '2026-07-20';

export const storyDesignDirection = Object.freeze({
  identity: 'The Black Archive',
  shell: 'hybrid-dark-shell-warm-paper',
  mobileStatus: 'deferred',
  prototypeArcId: 'yorknew-city',
  palette: Object.freeze({
    shell: '#0D0D10',
    elevated: '#17171C',
    paper: '#F1ECE2',
    paperDeep: '#E4DCCE',
    ink: '#181619',
    lightInk: '#EEE9DF',
    muted: '#99958E',
    darkLine: '#303037',
    lightLine: '#CFC6B8',
    primary: '#A12A38',
    primaryDeep: '#6E1825',
    structural: '#C29C57',
    information: '#557286',
    royal: '#705978',
  }),
  rules: Object.freeze([
    'Crimson is the global active color; green is contextual rather than structural.',
    'Dark surfaces own navigation, heroes, maps, diagrams, search, and major transitions.',
    'Warm paper surfaces own chronology, biography, source notes, tables, and long-form reading.',
    'Shared typography and layout establish one archive; each arc receives one controlled secondary accent and one primary interaction.',
    'Rounded pills are reserved for compact status and control states rather than used as the default container language.',
  ]),
});

export const storyRoutePolicy = Object.freeze({
  hubRoute: '/story',
  routeMode: 'clean-history-paths',
  currentMode: 'clean-history-router-live',
  directReloadRequired: true,
  historyFallbackRequired: true,
  preserveLegacyHashes: true,
  preserveQueryParameters: true,
  preserveSpoilerBoundary: true,
  nestedPageRule: 'Nested routes are allowed only when one arc subject has enough independent depth to justify a shareable page.',
});

export const storyContentPolicy = Object.freeze({
  factualSpine: 'manga',
  animeModel: 'inline-2011-adaptation-layer',
  analysisSeparation: Object.freeze([
    'factual-record',
    'structural-interpretation',
    'thematic-interpretation',
    'unresolved-question',
    'adaptation-note',
  ]),
  standardSections: Object.freeze([
    'overview',
    'context',
    'premise',
    'chronology',
    'characters',
    'factions',
    'locations',
    'conflicts',
    'nen',
    'objects',
    'themes',
    'aftermath',
    'adaptation',
    'sources',
  ]),
  chapterDepth: 'Arc pages own scoped chapter references; selected chapters may receive deep dossiers, but Chapters 1–339 are not automatically expanded into 339 full pages.',
});

const entry = (record) => Object.freeze({
  legacyRoutes: Object.freeze(record.legacyRoutes || []),
  accent: Object.freeze(record.accent),
  ...record,
});

export const storyEntries = Object.freeze([
  entry({
    id: 'volume-0',
    order: 0,
    type: 'prologue',
    title: 'Volume 0 · Kurapika’s Memories',
    shortTitle: 'Volume 0',
    route: '/story/volume-0',
    legacyRoutes: ['#/series/volume-0'],
    pageDepth: 'single-page',
    officialArcId: null,
    parentOfficialArcId: null,
    manga: Object.freeze({ label: 'Two supplementary chapters', pageRange: null, officialRange: null }),
    anime2011: null,
    previousId: null,
    nextId: 'hunter-exam',
    accent: { name: 'memory-scarlet', value: '#8E3B46' },
    source: 'https://hunterxhunter.fandom.com/wiki/Kurapika%27s_Memories',
    architectureNote: 'A Story prologue and Yorknew prerequisite, not a numbered official arc.',
  }),
  entry({
    id: 'hunter-exam',
    order: 1,
    type: 'official-arc-page',
    title: 'Hunter Exam',
    shortTitle: 'Hunter Exam',
    route: '/story/hunter-exam',
    legacyRoutes: ['#/series/hunter-exam'],
    pageDepth: 'single-page',
    officialArcId: 'hunter-exam',
    parentOfficialArcId: null,
    manga: Object.freeze({ label: 'Exam-focused editorial page', pageRange: [1, 38], officialRange: [1, 43] }),
    anime2011: Object.freeze({ pageRange: [1, 21], officialRange: [1, 26], supplementalEpisodes: [] }),
    previousId: 'volume-0',
    nextId: 'zoldyck-family',
    accent: { name: 'exam-gold', value: '#B47A35' },
    source: 'https://hunterxhunter.fandom.com/wiki/Hunter_Exam_arc',
    architectureNote: 'The official Hunter Exam boundary remains visible even though its Kukuroo Mountain conclusion receives a separate editorial page.',
  }),
  entry({
    id: 'zoldyck-family',
    order: 2,
    type: 'editorial-story-page',
    title: 'Zoldyck Family',
    shortTitle: 'Zoldyck Family',
    route: '/story/zoldyck-family',
    legacyRoutes: [],
    pageDepth: 'single-page',
    officialArcId: null,
    parentOfficialArcId: 'hunter-exam',
    manga: Object.freeze({ label: 'Editorial segment of the official Hunter Exam arc', pageRange: [39, 43], officialRange: [1, 43] }),
    anime2011: Object.freeze({ pageRange: [22, 25], officialRange: [1, 26], supplementalEpisodes: [26] }),
    previousId: 'hunter-exam',
    nextId: 'heavens-arena',
    accent: { name: 'zoldyck-violet', value: '#66516F' },
    source: 'https://hunterxhunter.fandom.com/wiki/Hunter_Exam_arc',
    architectureNote: 'A dedicated archive page for navigation and content depth, explicitly labeled as an editorial split rather than an eighth official arc.',
  }),
  entry({
    id: 'heavens-arena',
    order: 3,
    type: 'official-arc-page',
    title: 'Heavens Arena',
    shortTitle: 'Heavens Arena',
    route: '/story/heavens-arena',
    legacyRoutes: ['#/series/heavens-arena'],
    pageDepth: 'single-page',
    officialArcId: 'heavens-arena',
    parentOfficialArcId: null,
    manga: Object.freeze({ label: 'Official arc range', pageRange: [44, 63], officialRange: [44, 63] }),
    anime2011: Object.freeze({ pageRange: [27, 38], officialRange: [27, 38], supplementalEpisodes: [] }),
    previousId: 'zoldyck-family',
    nextId: 'yorknew-city',
    accent: { name: 'arena-cobalt', value: '#416A8A' },
    source: 'https://hunterxhunter.fandom.com/wiki/Heavens_Arena_arc',
    architectureNote: 'One comprehensive page built around the tower explorer, match ledger, rulebook, and Nen curriculum.',
  }),
  entry({
    id: 'yorknew-city',
    order: 4,
    type: 'official-arc-page',
    title: 'Yorknew City',
    shortTitle: 'Yorknew',
    route: '/story/yorknew-city',
    legacyRoutes: ['#/series/yorknew-city'],
    pageDepth: 'single-page',
    officialArcId: 'yorknew-city',
    parentOfficialArcId: null,
    manga: Object.freeze({ label: 'Official arc range', pageRange: [64, 119], officialRange: [64, 119] }),
    anime2011: Object.freeze({ pageRange: [39, 58], officialRange: [39, 58], supplementalEpisodes: [] }),
    previousId: 'heavens-arena',
    nextId: 'greed-island',
    accent: { name: 'yorknew-crimson', value: '#A12A38' },
    source: 'https://hunterxhunter.fandom.com/wiki/Yorknew_City_arc',
    architectureNote: 'The first implementation prototype and quality bar for the reusable arc-page system.',
  }),
  entry({
    id: 'greed-island',
    order: 5,
    type: 'official-arc-page',
    title: 'Greed Island',
    shortTitle: 'Greed Island',
    route: '/story/greed-island',
    legacyRoutes: ['#/series/greed-island'],
    pageDepth: 'single-page',
    officialArcId: 'greed-island',
    parentOfficialArcId: null,
    manga: Object.freeze({ label: 'Official arc range', pageRange: [120, 185], officialRange: [120, 185] }),
    anime2011: Object.freeze({ pageRange: [59, 75], officialRange: [59, 75], supplementalEpisodes: [] }),
    previousId: 'yorknew-city',
    nextId: 'chimera-ant',
    accent: { name: 'game-cyan', value: '#2D7F9A' },
    source: 'https://hunterxhunter.fandom.com/wiki/Greed_Island_arc',
    architectureNote: 'Electric blue, cyan, magenta, and card-paper replace green as the interface identity; terrain may remain contextually green.',
  }),
  entry({
    id: 'chimera-ant',
    order: 6,
    type: 'official-arc-page',
    title: 'Chimera Ant',
    shortTitle: 'Chimera Ant',
    route: '/story/chimera-ant',
    legacyRoutes: ['#/series/chimera-ant'],
    pageDepth: 'expandable',
    officialArcId: 'chimera-ant',
    parentOfficialArcId: null,
    manga: Object.freeze({ label: 'Official arc range', pageRange: [186, 318], officialRange: [186, 318] }),
    anime2011: Object.freeze({ pageRange: [76, 136], officialRange: [76, 136], supplementalEpisodes: [] }),
    previousId: 'greed-island',
    nextId: 'chairman-election',
    accent: { name: 'ant-ochre', value: '#AA7A2C' },
    source: 'https://hunterxhunter.fandom.com/wiki/Chimera_Ant_arc',
    architectureNote: 'Begins as one comprehensive route; nested pages are permitted only after content depth proves they are necessary.',
  }),
  entry({
    id: 'chairman-election',
    order: 7,
    type: 'official-arc-page',
    title: '13th Hunter Chairman Election',
    shortTitle: 'Chairman Election',
    route: '/story/chairman-election',
    legacyRoutes: ['#/series/chairman-election'],
    pageDepth: 'single-page',
    officialArcId: 'chairman-election',
    parentOfficialArcId: null,
    manga: Object.freeze({ label: 'Official arc range', pageRange: [319, 339], officialRange: [319, 339] }),
    anime2011: Object.freeze({ pageRange: [137, 148], officialRange: [137, 148], supplementalEpisodes: [] }),
    previousId: 'chimera-ant',
    nextId: 'succession-contest',
    accent: { name: 'election-navy', value: '#415B79' },
    source: 'https://hunterxhunter.fandom.com/wiki/13th_Hunter_Chairman_Election_arc',
    architectureNote: 'One synchronized page for the Association election and Killua–Alluka rescue timelines.',
  }),
  entry({
    id: 'succession-contest',
    order: 8,
    type: 'official-arc-archive',
    title: 'Succession Contest',
    shortTitle: 'Succession Contest',
    route: '/story/succession-contest',
    legacyRoutes: ['#/succession/overview'],
    pageDepth: 'multi-page',
    officialArcId: 'succession-contest',
    parentOfficialArcId: null,
    manga: Object.freeze({ label: 'Ongoing archive range', pageRange: [340, 413], officialRange: [340, 413] }),
    anime2011: null,
    previousId: 'chairman-election',
    nextId: null,
    accent: { name: 'succession-purple', value: '#705978' },
    source: 'https://hunterxhunter.fandom.com/wiki/Succession_Contest_arc',
    architectureNote: 'A landing page plus preserved deep subpages; it must not be compressed into the standard one-page arc template.',
  }),
]);

export const successionStorySubpages = Object.freeze([
  Object.freeze({ id: 'royal-family', route: '/story/succession-contest/royal-family', legacyRoute: '#/succession/family-tree' }),
  Object.freeze({ id: 'cast', route: '/story/succession-contest/cast', legacyRoute: '#/succession/succession-roster' }),
  Object.freeze({ id: 'timeline', route: '/story/succession-contest/timeline', legacyRoute: '#/succession/succession-timeline' }),
  Object.freeze({ id: 'black-whale', route: '/story/succession-contest/black-whale', legacyRoute: '#/succession/black-whale' }),
  Object.freeze({ id: 'nen-and-beasts', route: '/story/succession-contest/nen-and-beasts', legacyRoute: '#/succession/beasts' }),
  Object.freeze({ id: 'power-blocs', route: '/story/succession-contest/power-blocs', legacyRoute: '#/succession/mafia' }),
  Object.freeze({ id: 'records', route: '/story/succession-contest/records', legacyRoute: '#/succession/chapters' }),
]);

export const storyUtilityDestinations = Object.freeze([
  Object.freeze({ id: 'chronology', route: '/story?view=chronology', legacyRoute: '#/series/chronology' }),
  Object.freeze({ id: 'chapters', route: '/story?view=chapters', legacyRoute: '#/series/chapters' }),
  Object.freeze({ id: 'adaptation', route: '/story?view=adaptation', legacyRoute: '#/series/adaptation' }),
]);

export const storyArchitectureAcceptance = Object.freeze([
  'The Story hub exists at /story and acts as a directory rather than a container for every full arc experience.',
  'Every Story entry has one clean, directly reloadable route and reciprocal previous/next navigation.',
  'Zoldyck Family is a dedicated editorial page whose official Hunter Exam parentage remains explicit.',
  'Volume 0 is a prologue rather than a numbered official arc.',
  'The manga remains the factual spine and the 2011 anime remains an inline adaptation layer.',
  'Yorknew City is the first implementation prototype.',
  'Chimera Ant may gain nested routes only when independent content depth justifies them.',
  'Succession Contest retains its seven deep destinations beneath the unified Story hierarchy.',
  'The Black Archive hybrid dark-shell/warm-paper direction replaces green as the global identity.',
  'Mobile-specific implementation and acceptance work remain deferred until explicitly reopened.',
]);
