const encoder = new TextEncoder();

export const CHAPTER_BANK_START = 339;
export const CHAPTER_BANK_END = 414;
export const CHAPTER_BANK_TOTAL = CHAPTER_BANK_END - CHAPTER_BANK_START + 1;
export const CHAPTER_HISTORY_PATH = 'src/data/successionChapterImportHistory.generated.js';

const filenameFromPath = (src = '') => String(src).split('/').pop() || null;
const formatFromFilename = (filename = '') => {
  const extension = String(filename).toLowerCase().match(/\.([a-z0-9]+)$/)?.[1] || null;
  return extension === 'jpeg' ? 'jpg' : extension;
};

export const checksumBytes = async (bytes) => {
  const digest = new Uint8Array(await crypto.subtle.digest('SHA-256', bytes));
  return `sha256-${[...digest].map((value) => value.toString(16).padStart(2, '0')).join('')}`;
};

export const createChapterPageRecord = async ({ chapter, page, filename, src, sourceUrl, width, height, bytes, importedAt }) => ({
  id: `chapter-${chapter}-p${String(page).padStart(3, '0')}`,
  chapter,
  page,
  label: `p.${page}`,
  filename,
  src,
  localPath: src,
  sourceUrl,
  width,
  height,
  format: formatFromFilename(filename),
  byteSize: bytes.byteLength,
  checksum: await checksumBytes(bytes),
  status: 'published',
  importedAt,
});

export const parseGeneratedHistory = (source) => {
  const match = String(source).match(/export const successionChapterImportHistory = Object\.freeze\(([\s\S]*?)\);\s*$/);
  if (!match) throw new Error('The generated chapter history does not match the expected format.');
  return JSON.parse(match[1]);
};

export const serializeGeneratedHistory = (history) => `// Generated by Succession chapter import tools.\n// Importers append immutable audit records; do not edit entries by hand.\nexport const successionChapterImportHistory = Object.freeze(${JSON.stringify(history, null, 2)});\n`;

export const normalizeBankPage = (chapter, page, index) => {
  const pageNumber = Number.isInteger(page?.page) ? page.page : index + 1;
  const filename = page?.filename || filenameFromPath(page?.src);
  return {
    id: page?.id || `chapter-${chapter}-p${String(pageNumber).padStart(3, '0')}`,
    chapter,
    page: pageNumber,
    label: page?.label || `p.${pageNumber}`,
    filename,
    src: page?.src || null,
    localPath: page?.localPath || page?.src || null,
    sourceUrl: page?.sourceUrl || null,
    width: Number.isInteger(page?.width) ? page.width : null,
    height: Number.isInteger(page?.height) ? page.height : null,
    format: page?.format || formatFromFilename(filename),
    byteSize: Number.isInteger(page?.byteSize) ? page.byteSize : null,
    checksum: page?.checksum || null,
    status: page?.status || 'published',
    importedAt: page?.importedAt || null,
  };
};

export const buildChapterBank = (manifest = {}, history = []) => {
  const chapters = Array.from({ length: CHAPTER_BANK_TOTAL }, (_, offset) => {
    const chapter = CHAPTER_BANK_START + offset;
    const pages = [...(manifest[chapter] || [])]
      .sort((left, right) => left.page - right.page)
      .map((page, index) => normalizeBankPage(chapter, page, index));
    const latestHistory = history
      .filter((entry) => Number(entry.chapter) === chapter)
      .sort((left, right) => String(right.timestamp || '').localeCompare(String(left.timestamp || '')))[0] || null;
    const expectedPageCount = latestHistory?.expectedPageCount || pages.length || null;
    const missingPages = latestHistory?.missingPages || [];
    const status = pages.length
      ? (missingPages.length ? 'needs-repair' : (latestHistory?.status || 'published'))
      : 'empty';

    return {
      id: `chapter-${chapter}`,
      chapter,
      label: `Chapter ${chapter}`,
      pageCount: pages.length,
      storedPageCount: pages.length,
      expectedPageCount,
      missingPages,
      storage: pages.length ? 'local' : 'empty',
      status,
      sourceUrl: latestHistory?.sourceUrl || pages.find((page) => page.sourceUrl)?.sourceUrl || null,
      lastUpdated: latestHistory?.timestamp || pages.find((page) => page.importedAt)?.importedAt || null,
      latestCommitSha: latestHistory?.commitSha || null,
      pages,
    };
  });

  return {
    startChapter: CHAPTER_BANK_START,
    endChapter: CHAPTER_BANK_END,
    chapterCount: CHAPTER_BANK_TOTAL,
    storedChapterCount: chapters.filter((record) => record.pageCount > 0).length,
    emptyChapterCount: chapters.filter((record) => record.pageCount === 0).length,
    pageCount: chapters.reduce((total, record) => total + record.pageCount, 0),
    needsRepairCount: chapters.filter((record) => record.status === 'needs-repair').length,
    chapters,
    history: [...history].sort((left, right) => String(right.timestamp || '').localeCompare(String(left.timestamp || ''))),
  };
};

export const createImportHistoryRecord = ({ chapter, previousPageCount, newPageCount, sourceUrl, timestamp, commitSha = null }) => ({
  id: `chapter-${chapter}-${String(timestamp).replace(/[^0-9]/g, '')}`,
  action: previousPageCount ? 'replace-chapter' : 'import-chapter',
  chapter,
  previousPageCount,
  newPageCount,
  expectedPageCount: newPageCount,
  missingPages: [],
  status: 'published',
  sourceUrl,
  sourceType: 'remote-url',
  timestamp,
  commitSha,
});

export const validateBankChapter = (chapter) => Number.isInteger(chapter)
  && chapter >= CHAPTER_BANK_START
  && chapter <= CHAPTER_BANK_END;
